const QUOTES = [
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'Small daily improvements are the key to staggering long-term results.', author: 'Robin Sharma' },
  { text: 'Excellence is not a destination; it is a continuous journey that never ends.', author: 'Brian Tracy' },
  { text: 'Your work is going to fill a large part of your life. Make it great.', author: 'Steve Jobs' },
  { text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser' },
  { text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'Focus on being productive instead of busy.', author: 'Tim Ferriss' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Done is better than perfect.', author: 'Sheryl Sandberg' },
  { text: 'Progress, not perfection.', author: 'Unknown' },
  { text: 'Make each day your masterpiece.', author: 'John Wooden' },
  { text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { text: 'Hard work beats talent when talent doesn\'t work hard.', author: 'Tim Notke' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese proverb' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau' },
  { text: 'If you are not willing to risk the usual, you will have to settle for the ordinary.', author: 'Jim Rohn' },
  { text: 'Dream big. Start small. Act now.', author: 'Robin Sharma' },
  { text: 'What you get by achieving your goals is not as important as what you become.', author: 'Zig Ziglar' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin' },
  { text: 'Be so good they can\'t ignore you.', author: 'Steve Martin' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky' },
  { text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupéry' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent van Gogh' },
  { text: 'The only limit to our realization of tomorrow is our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
  { text: 'Either you run the day, or the day runs you.', author: 'Jim Rohn' },
  { text: 'What we fear doing most is usually what we most need to do.', author: 'Tim Ferriss' },
  { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'The harder you work for something, the greater you\'ll feel when you achieve it.', author: 'Unknown' },
  { text: 'Don\'t count the days. Make the days count.', author: 'Muhammad Ali' },
  { text: 'Every accomplishment starts with the decision to try.', author: 'Gail Devers' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.', author: 'Aristotle' },
  { text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington' },
  { text: 'The best preparation for tomorrow is doing your best today.', author: 'H. Jackson Brown Jr.' },
  { text: 'Motivation gets you going, but discipline keeps you growing.', author: 'John C. Maxwell' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb' },
  { text: 'A ship in harbor is safe, but that is not what ships are built for.', author: 'John A. Shedd' },
  { text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca' },
  { text: 'Keep your eyes on the stars, and your feet on the ground.', author: 'Theodore Roosevelt' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'You don\'t need to see the whole staircase, just take the first step.', author: 'Martin Luther King Jr.' },
  { text: 'Work hard in silence. Let success make the noise.', author: 'Frank Ocean' },
  { text: 'Today\'s accomplishments were yesterday\'s impossibilities.', author: 'Robert H. Schuller' },
  { text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown' },
  { text: 'Great minds discuss ideas; average minds discuss events; small minds discuss people.', author: 'Eleanor Roosevelt' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Opportunities are usually disguised as hard work, so most people don\'t recognize them.', author: 'Ann Landers' },
  { text: 'If you want something you\'ve never had, you must be willing to do something you\'ve never done.', author: 'Thomas Jefferson' },
  { text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon' },
  { text: 'Do something today that your future self will thank you for.', author: 'Unknown' },
  { text: 'Your limitation—it\'s only your imagination.', author: 'Unknown' },
  { text: 'Sometimes later becomes never. Do it now.', author: 'Unknown' },
  { text: 'Great things never come from comfort zones.', author: 'Unknown' },
  { text: 'Success doesn\'t just find you. You have to go out and get it.', author: 'Unknown' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
  { text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller' },
  { text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson' },
  { text: 'Success is liking yourself, liking what you do, and liking how you do it.', author: 'Maya Angelou' },
  { text: 'The way to achieve your own success is to be willing to help somebody else get it first.', author: 'Iyanla Vanzant' },
  { text: 'If you can dream it, you can do it.', author: 'Walt Disney' },
  { text: 'Nothing will work unless you do.', author: 'Maya Angelou' },
  { text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins' },
  { text: 'In the middle of every difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'You are braver than you believe, stronger than you seem, and smarter than you think.', author: 'A.A. Milne' },
  { text: 'Happiness is not something ready made. It comes from your own actions.', author: 'Dalai Lama' },
  { text: 'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', author: 'Winston Churchill' },
  { text: 'Try not to become a person of success, but rather try to become a person of value.', author: 'Albert Einstein' },
  { text: 'It is during our darkest moments that we must focus to see the light.', author: 'Aristotle' },
  { text: 'The only way of finding the limits of the possible is by going beyond them into the impossible.', author: 'Arthur C. Clarke' },
  { text: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', author: 'Vince Lombardi' },
  { text: 'Life is 10% what happens to us and 90% how we react to it.', author: 'Charles R. Swindoll' },
  { text: 'Change your thoughts and you change your world.', author: 'Norman Vincent Peale' },
  { text: 'Either write something worth reading or do something worth writing.', author: 'Benjamin Franklin' },
  { text: 'When you have a dream, you\'ve got to grab it and never let go.', author: 'Carol Burnett' },
  { text: 'Nothing is impossible. The word itself says "I\'m possible!"', author: 'Audrey Hepburn' },
  { text: 'There is nothing impossible to they who will try.', author: 'Alexander the Great' },
  { text: 'The bad news is time flies. The good news is you\'re the pilot.', author: 'Michael Altshuler' },
  { text: 'Life has got all those twists and turns. You\'ve got to hold on tight and off you go.', author: 'Nicole Kidman' },
  { text: 'Keep your face always toward the sunshine, and shadows will fall behind you.', author: 'Walt Whitman' },
  { text: 'You define your own life. Don\'t let other people write your script.', author: 'Oprah Winfrey' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'Malala Yousafzai' },
  { text: 'At the end of the day, whether or not those people are comfortable with how you\'re living your life doesn\'t matter. What matters is whether you\'re comfortable with it.', author: 'Dr. Phil' },
  { text: 'For me, becoming isn\'t about arriving somewhere or achieving a certain aim. I see it instead as forward motion, a means of evolving, a way to reach continuously toward a better self.', author: 'Michelle Obama' },
  { text: 'Spread love everywhere you go.', author: 'Mother Teresa' },
  { text: 'Do not allow people to dim your shine because they are blinded. Tell them to put some sunglasses on.', author: 'Lady Gaga' },
  { text: 'If you make your internal life a priority, then everything else you need on the outside will be given to you and it will be extremely clear what the next step is.', author: 'Gabrielle Bernstein' },
  { text: 'You don\'t always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens.', author: 'Regina Brett' },
  { text: 'My mission in life is not merely to survive, but to thrive.', author: 'Maya Angelou' },
  { text: 'You are enough just as you are.', author: 'Meghan Markle' },
  { text: 'The most wasted of days is one without laughter.', author: 'E.E. Cummings' },
  { text: 'You must do the things you think you cannot do.', author: 'Eleanor Roosevelt' },
  { text: 'It is never too late to be what you might have been.', author: 'George Eliot' },
  { text: 'You do not find the happy life. You make it.', author: 'Camilla Eyring Kimball' },
  { text: 'Stay close to anything that makes you glad you are alive.', author: 'Hafiz' },
  { text: 'Some people look for a beautiful place. Others make a place beautiful.', author: 'Hazrat Inayat Khan' },
  { text: 'Happiness often sneaks in through a door you didn\'t know you left open.', author: 'John Barrymore' },
  { text: 'Keep a green tree in your heart and perhaps a singing bird will come.', author: 'Chinese proverb' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'The purpose of our lives is to be happy.', author: 'Dalai Lama' },
  { text: 'Get busy living or get busy dying.', author: 'Stephen King' },
  { text: 'You only live once, but if you do it right, once is enough.', author: 'Mae West' },
  { text: 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas Edison' },
  { text: 'If you set your goals ridiculously high and it\'s a failure, you will fail above everyone else\'s success.', author: 'James Cameron' },
  { text: 'Life is what happens when you\'re busy making other plans.', author: 'John Lennon' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.', author: 'Helen Keller' },
  { text: 'It is not the length of life, but depth of life.', author: 'Ralph Waldo Emerson' },
  { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { text: 'Whether you think you can or you think you can\'t, you\'re right.', author: 'Henry Ford' },
  { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'In three words I can sum up everything I\'ve learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'The measure of who we are is what we do with what we have.', author: 'Vince Lombardi' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'If you want to go fast, go alone. If you want to go far, go together.', author: 'African proverb' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'An unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Happiness is not by chance, but by choice.', author: 'Jim Rohn' },
  { text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair' },
  { text: 'Begin anywhere.', author: 'John Cage' },
  { text: 'Courage is resistance to fear, mastery of fear — not absence of fear.', author: 'Mark Twain' },
  { text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
  { text: 'Every moment is a fresh beginning.', author: 'T.S. Eliot' },
  { text: 'Never regret anything that made you smile.', author: 'Mark Twain' },
  { text: 'Die with memories, not dreams.', author: 'Unknown' },
  { text: 'What we think, we become.', author: 'Buddha' },
  { text: 'All our dreams can come true if we have the courage to pursue them.', author: 'Walt Disney' },
  { text: 'The only thing standing between you and your goal is the story you keep telling yourself.', author: 'Jordan Belfort' },
  { text: 'Creativity is intelligence having fun.', author: 'Albert Einstein' },
  { text: 'What you do today can improve all your tomorrows.', author: 'Ralph Marston' },
  { text: 'Without hustle, talent will only carry you so far.', author: 'Gary Vaynerchuk' },
  { text: 'Work hard, stay humble.', author: 'Unknown' },
  { text: 'Hustle until you no longer need to introduce yourself.', author: 'Unknown' },
  { text: 'Build your own dreams, or someone else will hire you to build theirs.', author: 'Farrah Gray' },
  { text: 'The struggle you\'re in today is developing the strength you need for tomorrow.', author: 'Unknown' },
  { text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', author: 'Unknown' },
  { text: 'Wake up with determination. Go to bed with satisfaction.', author: 'Unknown' },
  { text: 'Do something worth remembering.', author: 'Elvis Presley' },
  { text: 'It\'s going to be hard, but hard does not mean impossible.', author: 'Unknown' },
  { text: 'Don\'t limit your challenges. Challenge your limits.', author: 'Unknown' },
  { text: 'The key to success is to focus on goals, not obstacles.', author: 'Unknown' },
  { text: 'Dream it. Wish it. Do it.', author: 'Unknown' },
  { text: 'Success doesn\'t come to you. You go to it.', author: 'Marva Collins' },
  { text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
  { text: 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', author: 'Roy T. Bennett' },
  { text: 'Work until your idols become your rivals.', author: 'Unknown' },
  { text: 'Stars can\'t shine without darkness.', author: 'Unknown' },
  { text: 'Be a voice, not an echo.', author: 'Albert Einstein' },
  { text: 'Make today so awesome that yesterday gets jealous.', author: 'Unknown' },
  { text: 'She believed she could, so she did.', author: 'Unknown' },
  { text: 'The comeback is always stronger than the setback.', author: 'Unknown' },
  { text: 'Prove them wrong.', author: 'Unknown' },
  { text: 'One day or day one. You decide.', author: 'Unknown' },
  { text: 'Today is your opportunity to build the tomorrow you want.', author: 'Ken Poirot' },
  { text: 'When you feel like quitting, think about why you started.', author: 'Unknown' },
  { text: 'Great things take time.', author: 'Unknown' },
  { text: 'Stay patient and trust your journey.', author: 'Unknown' },
  { text: 'Good things come to those who hustle.', author: 'Unknown' },
  { text: 'Make it happen. Shock everyone.', author: 'Unknown' },
  { text: 'The grind never stops.', author: 'Unknown' },
  { text: 'Winners are not people who never fail, but people who never quit.', author: 'Unknown' },
  { text: 'Your only limit is you.', author: 'Unknown' },
  { text: 'Be stronger than your excuses.', author: 'Unknown' },
  { text: 'Doubt kills more dreams than failure ever will.', author: 'Suzy Kassem' },
  { text: 'Invest in your dreams. Grind now. Shine later.', author: 'Unknown' },
  { text: 'Hustle in silence and let your success be the noise.', author: 'Unknown' },
  { text: 'Make every day count.', author: 'Unknown' },
  { text: 'Today\'s quote is tomorrow\'s memory — make it a good one.', author: 'Proto Team' },
  { text: 'Every order shipped is a promise kept.', author: 'Proto Team' },
  { text: 'Behind every great catalogue is a team that cares.', author: 'Proto Team' },
  { text: 'Precision today, trust tomorrow.', author: 'Proto Team' },
  { text: 'Show up. Ship it. Repeat.', author: 'Proto Team' },
  { text: 'The details are not the details. They make the design.', author: 'Charles Eames' },
  { text: 'Good service is good business.', author: 'Siebel Ad Server' },
  { text: 'Customers may forget what you said, but they\'ll never forget how you made them feel.', author: 'Maya Angelou' },
  { text: 'Retail is detail.', author: 'Unknown' },
  { text: 'Stock well. Serve well.', author: 'Proto Team' },
  { text: 'One product at a time, one customer at a time.', author: 'Proto Team' },
  { text: 'Consistency beats intensity.', author: 'Unknown' },
  { text: 'Clear shelves, clear mind.', author: 'Proto Team' },
  { text: 'Today\'s effort is tomorrow\'s edge.', author: 'Proto Team' },
  { text: 'Build the catalogue you\'d want to buy from.', author: 'Proto Team' },
  { text: 'Trust is earned in deliveries, not in promises.', author: 'Proto Team' },
  { text: 'Make the complex simple. That\'s the work.', author: 'Proto Team' },
  { text: 'Start the day with intent. End it with impact.', author: 'Proto Team' },
  { text: 'Your standards set the floor for everyone else.', author: 'Proto Team' },
  { text: 'Small fixes compound into big wins.', author: 'Proto Team' },
  { text: 'The best teams make hard things look easy.', author: 'Proto Team' },
  { text: 'Done beats perfect — but never beats careless.', author: 'Proto Team' },
  { text: 'Lead with clarity. Follow through with care.', author: 'Proto Team' },
  { text: 'Every SKU tells a story. Tell it well.', author: 'Proto Team' },
  { text: 'Momentum is built one task at a time.', author: 'Proto Team' },
  { text: 'Show up ready. Leave it better.', author: 'Proto Team' },
  { text: 'Excellence is a team sport.', author: 'Proto Team' },
  { text: 'Today is a good day to get ahead.', author: 'Proto Team' },
  { text: 'Focus on what moves the needle.', author: 'Proto Team' },
  { text: 'Quality work speaks louder than loud work.', author: 'Proto Team' },
  { text: 'Keep the standard high and the noise low.', author: 'Proto Team' },
  { text: 'Progress beats perfection every time.', author: 'Proto Team' },
  { text: 'Make today worth repeating tomorrow.', author: 'Proto Team' },
  { text: 'The work matters. So do you.', author: 'Proto Team' },
  { text: 'Bring your best — the team is counting on it.', author: 'Proto Team' },
  { text: 'Turn problems into processes.', author: 'Proto Team' },
  { text: 'Stay curious. Stay sharp.', author: 'Proto Team' },
  { text: 'Good enough never is — but good is a great start.', author: 'Proto Team' },
  { text: 'Win the morning, win the day.', author: 'Proto Team' },
  { text: 'Ship with pride.', author: 'Proto Team' },
  { text: 'Calm minds build strong systems.', author: 'Proto Team' },
  { text: 'Attention to detail is a superpower.', author: 'Proto Team' },
  { text: 'Build habits that outlast motivation.', author: 'Proto Team' },
  { text: 'The grind is real. So is the growth.', author: 'Proto Team' },
  { text: 'Make it work. Then make it better.', author: 'Proto Team' },
  { text: 'Today\'s discipline is tomorrow\'s freedom.', author: 'Proto Team' },
  { text: 'Keep going — you\'re closer than you think.', author: 'Proto Team' },
  { text: 'Raise the bar. Then clear it.', author: 'Proto Team' },
  { text: 'Simple tools, serious results.', author: 'Proto Team' },
  { text: 'Own the outcome.', author: 'Proto Team' },
  { text: 'Better every day, not someday.', author: 'Proto Team' },
  { text: 'The team that ships together wins together.', author: 'Proto Team' },
  { text: 'Start strong. Finish stronger.', author: 'Proto Team' },
  { text: 'Make excellence routine.', author: 'Proto Team' },
  { text: 'Your work ripples further than you know.', author: 'Proto Team' },
  { text: 'Stay ready so you never have to get ready.', author: 'Proto Team' },
  { text: 'Clear goals. Clean execution.', author: 'Proto Team' },
  { text: 'Today is day one of something great.', author: 'Proto Team' },
  { text: 'Put in the reps. Earn the results.', author: 'Proto Team' },
  { text: 'Trust the process. Respect the pace.', author: 'Proto Team' },
  { text: 'Build something you\'re proud to sign your name to.', author: 'Proto Team' },
  { text: 'Keep moving forward — that\'s the whole game.', author: 'Proto Team' },
  { text: 'Make today legendary.', author: 'Proto Team' },
  { text: 'You\'ve got this.', author: 'Proto Team' },
];

function dayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

/** Same quote all day (local timezone), rotates through the list across the year. */
export function getDailyQuote(date = new Date()) {
  return QUOTES[dayOfYear(date) % QUOTES.length];
}
